# Generated by Django 4.2.3 on 2023-08-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.IntegerField(verbose_name='Concurso')),
                ('content_json', models.JSONField(verbose_name='Conteúdo')),
            ],
        ),
    ]
