# Generated by Django 4.2.3 on 2023-08-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_json', models.JSONField(verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Sumario',
            },
        ),
        migrations.AlterModelOptions(
            name='lines',
            options={'verbose_name': 'Concurso'},
        ),
    ]
