# Generated by Django 4.2.3 on 2023-08-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_summary_alter_lines_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='data')),
                ('content_json', models.JSONField(verbose_name='Numeros')),
            ],
            options={
                'verbose_name': 'Jogos',
            },
        ),
    ]
